"""empty message

Revision ID: 169103a5a4ab
Revises: 6e326128dcb6
Create Date: 2018-06-16 20:40:34.000375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169103a5a4ab'
down_revision = '6e326128dcb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TBRegistroDias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBRegistroDias',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('datahr_inicio', sa.DATETIME(), nullable=True),
    sa.Column('datahr_fim', sa.DATETIME(), nullable=True),
    sa.Column('descricao', sa.VARCHAR(length=256), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('relUsuProj_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['relUsuProj_id'], ['TBRelUsuProj.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
