"""empty message

Revision ID: 23671695af63
Revises: 22dd1484ce37
Create Date: 2018-06-17 21:10:31.707023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23671695af63'
down_revision = '22dd1484ce37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBAtividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricaoAtiv', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TBRegistroDias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datahr_inicio', sa.String(length=19), nullable=True),
    sa.Column('datahr_fim', sa.String(length=19), nullable=True),
    sa.Column('descricao', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['TBAtividades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TBRegistroDias')
    op.drop_table('TBAtividades')
    # ### end Alembic commands ###
