"""empty message

Revision ID: 38e2a91bbc88
Revises: 
Create Date: 2018-05-22 16:05:00.677585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e2a91bbc88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBCliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpfCnpj', sa.String(length=14), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('tipoPessoa', sa.String(length=1), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpfCnpj'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TBCliente')
    # ### end Alembic commands ###
