"""empty message

Revision ID: 4472dac3ce0d
Revises: 5422092720b3
Create Date: 2018-06-05 03:00:42.351618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4472dac3ce0d'
down_revision = '5422092720b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TBRelUsuProj', schema=None) as batch_op:
        batch_op.drop_column('projeto_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TBRelUsuProj', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('projeto_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
