"""empty message

Revision ID: 5a197722102c
Revises: e49c5a4d66dd
Create Date: 2018-06-05 22:37:45.354389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a197722102c'
down_revision = 'e49c5a4d66dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBRelUsuProj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('is_coordenador', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['TBProjeto.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TBRelUsuProj')
    # ### end Alembic commands ###
