"""empty message

Revision ID: 6e326128dcb6
Revises: 5a197722102c
Create Date: 2018-06-16 20:05:45.165050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e326128dcb6'
down_revision = '5a197722102c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBRegistroDias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datahr_inicio', sa.DateTime(), nullable=True),
    sa.Column('datahr_fim', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('relUsuProj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['relUsuProj_id'], ['TBRelUsuProj.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TBRegistroDias')
    # ### end Alembic commands ###
