"""empty message

Revision ID: 72f07483ccf5
Revises: bcba03e9c829
Create Date: 2018-06-17 22:11:53.615854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f07483ccf5'
down_revision = 'bcba03e9c829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TBRegistroDias', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TBRegistroDias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
