"""empty message

Revision ID: 7fafb31c0e7a
Revises: a786032aeab9
Create Date: 2018-06-17 00:57:40.726456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fafb31c0e7a'
down_revision = 'a786032aeab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TBRegistroDias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBRegistroDias',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('datahr_inicio', sa.DATETIME(), nullable=True),
    sa.Column('datahr_fim', sa.DATETIME(), nullable=True),
    sa.Column('descricao', sa.VARCHAR(length=256), nullable=True),
    sa.Column('relUsuProj_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['relUsuProj_id'], ['TBRelUsuProj.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
