"""empty message

Revision ID: 81acfa0a00df
Revises: 38e2a91bbc88
Create Date: 2018-05-31 23:24:16.768854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81acfa0a00df'
down_revision = '38e2a91bbc88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBProjeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=256), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['TBCliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TBProjeto')
    # ### end Alembic commands ###
