"""empty message

Revision ID: a12e9b34f89b
Revises: ba95d5834f5a
Create Date: 2018-06-17 13:27:35.382876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12e9b34f89b'
down_revision = 'ba95d5834f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TBProjeto', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TBProjeto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.VARCHAR(length=256), nullable=False))

    # ### end Alembic commands ###
