"""empty message

Revision ID: a786032aeab9
Revises: 169103a5a4ab
Create Date: 2018-06-16 20:40:53.613960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a786032aeab9'
down_revision = '169103a5a4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBRegistroDias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datahr_inicio', sa.DateTime(), nullable=True),
    sa.Column('datahr_fim', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(length=256), nullable=True),
    sa.Column('relUsuProj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['relUsuProj_id'], ['TBRelUsuProj.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TBRegistroDias')
    # ### end Alembic commands ###
