"""empty message

Revision ID: a7ce834a8f6d
Revises: f56efb23d59f
Create Date: 2018-06-17 13:47:41.475174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ce834a8f6d'
down_revision = 'f56efb23d59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TBProjeto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricaoProj', sa.String(length=256), nullable=True))
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TBProjeto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('descricaoProj')

    # ### end Alembic commands ###
