"""empty message

Revision ID: addf3b227554
Revises: 72f07483ccf5
Create Date: 2018-06-17 22:13:24.370133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'addf3b227554'
down_revision = '72f07483ccf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TBRegistroDias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TBRegistroDias', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
