"""empty message

Revision ID: bcba03e9c829
Revises: 23671695af63
Create Date: 2018-06-17 21:44:09.901813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcba03e9c829'
down_revision = '23671695af63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TBAtividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricaoAtv', sa.String(length=32), nullable=True))
        batch_op.drop_column('descricaoAtiv')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TBAtividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricaoAtiv', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_column('descricaoAtv')

    # ### end Alembic commands ###
