"""empty message

Revision ID: e49c5a4d66dd
Revises: 6cb559d4826c
Create Date: 2018-06-05 22:27:27.964293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49c5a4d66dd'
down_revision = '6cb559d4826c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TBRelUsuProj')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBRelUsuProj',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_user', sa.INTEGER(), nullable=True),
    sa.Column('id_projeto', sa.INTEGER(), nullable=True),
    sa.Column('is_coordenador', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('is_coordenador IN (0, 1)'),
    sa.ForeignKeyConstraint(['id_projeto'], ['TBProjeto.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
