"""empty message

Revision ID: f56efb23d59f
Revises: c4a205d5aa23
Create Date: 2018-06-17 13:37:53.787688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56efb23d59f'
down_revision = 'c4a205d5aa23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TBProjeto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.String(length=256), nullable=True))
        batch_op.drop_column('descricaoProj')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TBProjeto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricaoProj', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
